### ISSUE TITLE
Proposition : add a game configuration screen

### ISSUE THREAD

**Issue by WaffleBuffer** [schwabdidier/GazePlay#168]
Adding a configuration screen before launching a game would allow factorization of game mode (for example game size for blocks).
However, this would induce refactoring a lot of existing code (how a game launch, create a "default" config screen) also, you should make sure that existing games still launch (with a dummy screen for example that would take no input and just have a play button).

**Comment by schwabdidier** [comment]
Why not if it is linked to issue #2

**Comment by YannRobert** [comment]
This idea needs to be digged up.

At first, I'm afraid it would make the game a little too complex to use (and code), if there is more configuration screens.

Issue #2 would be a good start.

In ```GameSpec``` you have ```variationHint``` that allows to make multiple variant of the same game.

I add something in mind about #2 that would probably cover part of current issue #168.

First use something like a FlowPane or GridPane, instead of a CheckBox, in order to render the list of games.

Then, in a second change, only render the distinct games without the variants. Then when a game is selected, variants list shows up (like 2x2, 2x3, 3x3, ...), then you choose the variant you want.
It would probably be similar to a XrossMediaBar [1]

That's a suggestion I wanted to discuss for some time now.

[1] https://fr.wikipedia.org/wiki/XrossMediaBar

**Comment by WaffleBuffer** [comment]
Actually, when i thought about a configuration screen, i thought about a kind of GridLayout (like you proposed for home screen) but with all variant. In the end, it would look like the home screen but instead of all games you would have the variants of the selected game. The goal is to be able to easily select variant with an eye tracker.
Also, we could also put here some more advanced game specific options like personal folder for the "where is ?" game for example. 
Those advanced options would be used with a mouse but this would be done by another user than the actual player (whose in the end will be a child).

**Comment by WaffleBuffer** [comment]
I've implemented a working configuration screen for Magic Card (it needs some little tweaks but it's actually working). You can find it on my forked repo under configScreen branch : 
https://github.com/WaffleBuffer/GazePlay/tree/ConfigScreen%23168
Is this a viable solution ?

**Comment by schwabdidier** [comment]
It is certainly possible to see that directly in your version of GazePlay but I know how to do with a pull request

**Comment by schwabdidier** [comment]
Ok, I found how to do, next time don't need to  pull :)

**Comment by schwabdidier** [comment]
Good job !
I think the more difficult has been done. 

Maybe we can draw instead of text ? I mean a picture/photo/screenshot with 2*2 cards, 2*3 cards,...

**Comment by schwabdidier** [comment]
done (long time ago)
