### ISSUE TITLE
Game idea : Breaker

### ISSUE THREAD

**Issue by Skullhack** [schwabdidier/GazePlay#180]
This is a game idea I had for GazePlay : a brick breaker game (like Breakout or Arkanoid). The paddle will be controlled by eye-tracking. I'm not sure if it's the kind of game that fit the software in terms of difficulty, but it can be configured to adapt to the player.

The settings I can think of :
     - Different levels with varying difficulties
     - The starting size of the paddle and it's color
     - The color, size and speed of the ball

A simple level editor could also be added.

**Comment by YannRobert** [comment]
I had the same idea some time ago.

This could be fun, but I am not sure this type of game is not really suitable with eye tracking.

When you look at the bricks at the top, or the ball that is moving, you do not look at the paddle.

Your gaze tends to look at many locations in the screen in order to prepare where you want to aim, so doing may move the paddle while you want it to just stay where it is.

I'd be glad if this can be done.

Also, this kind of game requires the user to be really focused in order to avoid loosing.
As soon as you look outside the screen, you loose. So it may not be suitable for many disabilities.

After I thought about that, I thought we could think of a variant of the original game where you cannot lose, or where you mitigate the consequences of missing the ball.

Also, I thought of a simpler game, that I would have called "the eyes of Superman" (reference to the ```heat vision``` of Superman) where you just break bricks with your gaze, that throws 2 red lasers coming from the user to the bricks.

**Comment by schwabdidier** [comment]
@Skullhack nothing to add to @YannRobert's point of view
