### ISSUE TITLE
BackGround music : configuration menu

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#252]
several options should be in the configuration

always stopped
stopped in all games
stopped in "cognitives games" (where is it for instance)
never stopped

**Comment by WaffleBuffer** [comment]
Is it really necessary as there is a volume box in every game ?

**Comment by YannRobert** [comment]
configuration should contain a "disable all background music" 
so that the music is not even started (nor downloaded on first use)
for people having issues with downloading music
or for people that don't want to turn on sound by mistake

also, the volume setting is not persistent for the moment, it should survive application restart, by saving the volume setting in configuration

**Comment by YannRobert** [comment]
people with this kind of issue : #259
would probably want to disable background music in configuration

**Comment by WaffleBuffer** [comment]
Also, maybe add a volume icon next to the slider so when it's clicked, it mutes the volume.

**Comment by schwabdidier** [comment]
done
