### ISSUE TITLE
Color : can't select buttons in the bottom side of the right bar

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#395]
the bottom bar always covers it

**Comment by schwabdidier** [comment]
@WaffleBuffer

**Comment by WaffleBuffer** [comment]
What is the point of having a hiding panel at the bottom if we can't have things behind it ? What about reducing the size of the main graphical context. Or maybe make the panel appears only when the cursor (gaze or mouse) is reaching the bottom part of the panel.

**Comment by kuhlkrein** [comment]
I was thinking about it when I modified this bar, maybe we can create a small area ( at the bottom right for example) that will open the  panel instead of open it when going on the whole bottom part. 
(like the small part on bottom right of windows computer for hiding the windows and going to desktop..). Else, I did this thing in a project with @MelanieCarriere : 

![image](https://user-images.githubusercontent.com/24478346/40228355-5a75e470-5a91-11e8-94ed-de5d3538ae1c.png)

![image](https://user-images.githubusercontent.com/24478346/40228371-63179dee-5a91-11e8-9d68-ac156d6278af.png)

What do you think @schwabdidier  ?

**Comment by schwabdidier** [comment]
Nice idea, isn't it @YannRobert  ?

**Comment by schwabdidier** [comment]
Nice idea, isn't it @YannRobert ?

**Comment by YannRobert** [comment]
I have not pull for a while. I just pulled and tried the new code.

I did not know there was change that made the bottom control bar over the game context, instead of under it.
Can you please reference the PR that did this ?

Obviously this is causing new kinds of issues, because the control bar appears over the game every time you point to the bottom on the screen.
The way I see it, this is a blocking issue, because most of the games are now unusable.

I have not tried it with the eyetracker device yet, but I guess this is even worse with it, because gaze will look at this part of the screen even when the user does not intend to use the control bar.

Maybe the change should be reverted for the moment.

**Comment by kuhlkrein** [comment]
It's me @YannRobert , I'm planning to create a smaller "button" option as described just before that will not interfer with the game context.

**Comment by WaffleBuffer** [comment]
I think this issue can be closed
