### ISSUE TITLE
5 different games : addition, soustraction, multiplication, division and all

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#697]
It would be better in order to learn only one operation at the same time.

Should be resolved by @wafaahs

**Comment by wafaahs** [comment]
Okay I'll be on it! 
I wanted to get your feedback first before I do the rest.

**Comment by wafaahs** [comment]
Dr. Should I also have variations of the games that allow for negative values? 
Right now the game only has positive values to make it simpler for the kids.. 
so for example when the equation is randomly generated as  "5-7" I am switching it to "7-5" so that the answer will not be negative. 
Should I have a different variation or game version that allows for the  negative values?

**Comment by schwabdidier** [comment]
No negative value for now, it is too difficult

**Comment by wafaahs** [comment]
Dr. for the math games, should we create a new game category for "logic" (or maybe math?)? 
I currently put the games under memorization, but I am not sure if that is really adequate.

**Comment by schwabdidier** [comment]
It is a very interesting question. Add an issue for it for now and let's think about it. I close this issue.

**Comment by schwabdidier** [comment]
Resolved with pull request #706
