### ISSUE TITLE
Game Scene Image not showing behind Heatmap/FixationSequence

### ISSUE THREAD

**Issue by johzz-o2** [schwabdidier/GazePlay#752]
the screenshot for some games doesn't show the game content (for example this was sliding puzzles game) and also maybe it would be better to remove the configuration button from the screenshot
![Screenshot from 2019-05-28 18-19-38](https://user-images.githubusercontent.com/40126702/58488677-0d3b0900-816a-11e9-8bf3-0ba8d26d5ba6.png)

**Comment by teoblachere** [comment]
The problem is that I have to take the screenshot once the game is launched and rendered, so I'm taking it at the beginning of a round, but not every game uses that function, so yeah I need to find another way.
As for button, I'll see what I can do, but it might get tricky.
I'll work on it tomorrow, thanks for the feedback.
