### ISSUE TITLE
3 games are missing

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#896]
We have no longer Creampie, ninja and another one since last commit.

**Comment by schwabdidier** [comment]
We could also add the egg game (I forgot it last release)

**Comment by YannRobert** [comment]
I don't think so, I can see those games available in the menu

Just keep in mind that since #895 the menu is dynamically generated, it is not hard coded anymore, which is a good thing. 
But this has an influence on ordering in the games list. As the list was ordered respectfully with the order items where added in the list by the hard code.

Ordering of games list should not be a matter on the way it is programmed.
It should rather be sorted on some easily understandable properties of the games, like the category or the game name.

So right now the list is sorted by category then by namecode of the game.
We can improve that, like sorting on the game label (after translation to the user language).

**Comment by schwabdidier** [comment]
oh, you are right. I am not able to count, there are 19 lines, not 18.

Very good ! I found them :)
