### ISSUE TITLE
version in the licence and the log file

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#90]
Question to @YannRobert 

For instance, in the log file, Version : 1.0.6-SNAPSHOT (2017-11-15T07:56:55Z). 

Is it possible to have Version : 1.0.6 (2017-11-15T07:56:55Z) ?

**Comment by YannRobert** [comment]
Hi Didier,

It's simple, the version you get, in the manifest and license files, is the same as the version that was built.
So it you want version ```1.0.6```, you need to build the project with that version ```1.0.6``` in ```pom.xml``` files.

A ```-SNAPSHOT``` version is a build that is not tagged in SCM. When looking at a ```-SNAPSHOT``` binaries, the exact commit is unspecified.

That is opposed to a released version : a released version is tagged in SCM, and binaries are built from sources with this tag. So that anyone could rebuild the same binaries from the tag.

You should never use the same version number for different binaries. Once a tag it set to a commit, it should never be changed to an other commit. Otherwise people can get confused.

You should never distribute ```-SNAPSHOT``` binaries. As it would be too difficult to track the exact version of the code that was used to build it. So when you get a bug report from a user using a ```-SNAPSHOT``` version, it's difficult to track the issue.

When you feel the need to distribute binaries, you must release. Even it you release every day or multiple times a day. Even if you release for only one particular user. That does not matter. What matters is that users (and you) can track the exact version of every binaries that were ever distributed.

The maven-release-plugin assists you in updating the version in the pom, and even does the tagging in the SCM. You really should use the command line from ```BUILD.MD``` [1] (the third chapter of the document).

[1] https://github.com/schwabdidier/GazePlay/blob/master/BUILD.MD#how-to-release-the-software-for-version-tagging-in-official-scm-and-binaries-distribution

**Comment by schwabdidier** [comment]
Thank you for your clear explanations !
